### PR TITLE
Support for loading SVG from Blob or resources (Android)

### PR DESCRIPTION
**Pull request by falkolab**
I did refactoring and added other source for SVG like Blob.
Can you extend iOS functionality in this way?

With this functionality we can set and update svg without storing it to a file.

Change color:

``` javascript
var file = Ti.Filesystem.getFile('images/myimage.svg');
var blob = file.read();
var source = blob.text;
source = source.replace("#315b09", "#000000");
$.svg.image = Ti.createBuffer({value: source}).toBlob();
```

Or set image value directly from HTTPClient response or generate it in application.

### CODE REVIEW

**Comment by icecandy** [comment]
@falkolab. I think this module needs refactoring as it does not fail gracefully if the image file is not found - basically crashes the app. I am struggling to get it to work with Tishadow (actually I can make it work on iOS but not Android at the moment) as I believe the module accepts local file paths and not global and therefore causes a problem in tishadow (which changes absolute paths of files in the compile). Maybe your new source type will solve that problem so I will try it out.

**Comment by GeraudBourdin** [comment]
hey i didn't saw this PR !! Thanks a lot  ! I will have a look at the code and release an updated package/ I am so sorry that these time i do not have time for open source. So i can't work on modules. 
Thanks a lot @falkolab  !! :)
@icecandy : You have to know that this module is based on open sourced lib's that i can't change myself ! :/

**Comment by falkolab** [comment]
@GeraudBourdin Please update ios module to support blobs as source and level of modules versions

**Comment by icecandy** [comment]
That would be nice :) I think Geraud is very busy though.

**Comment by falkolab** [comment]
Сan anyone help him?

**Pull request merged**
